steps:
 - name: gcr.io/k8s-skaffold/pack
   args:
     - '--env=GOOGLE_BUILDABLE=src/Web'
     - '--env=GOOGLE_ENTRYPOINT=cd bin && dotnet Web.dll'
     - build
     - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
     - '--builder=gcr.io/buildpacks/builder:v1'
     - '--path=.'
   id: Buildpack
   entrypoint: pack
 - name: gcr.io/cloud-builders/docker
   args:
     - push
     - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
   id: Push
 - name: gcr.io/google.com/cloudsdktool/cloud-sdk
   args:
     - run
     - services
     - update
     - $_SERVICE_NAME
     - '--platform=managed'
     - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
     - >-
       --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
     - '--region=$_DEPLOY_REGION'
     - '--quiet'
   id: Deploy
   entrypoint: gcloud
images:
 - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
 substitutionOption: ALLOW_LOOSE
substitutions:
 _SERVICE_NAME: eshop-on-web
 _DEPLOY_REGION: asia-east1
 _GCR_HOSTNAME: asia.gcr.io
 _LABELS: gcb-trigger-id=3b72e381-3dbb-4dab-bb7c-3ff770c8555b
 _TRIGGER_ID: 3b72e381-3dbb-4dab-bb7c-3ff770c8555b
 _PLATFORM: managed
tags:
 - gcp-cloud-build-deploy-cloud-run
 - gcp-cloud-build-deploy-cloud-run-managed
 - eshop-on-web
